{{- if .Values.redis.enabled }}
{{- with mergeOverwrite (deepCopy .Values.global) .Values.redis }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: burrito-redis
  annotations:
    {{- toYaml .metadata.annotations | nindent 4 }}
  labels:
    {{- toYaml .metadata.labels | nindent 4 }}
spec:
  {{- if not .deployment.autoscaling.enabled }}
  replicas: {{ .deployment.replicas }}
  {{- end }}
  selector:
    matchLabels:
      {{- toYaml .metadata.labels | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- toYaml .deployment.podAnnotations | nindent 8 }}
      labels:
        {{- toYaml .metadata.labels | nindent 8 }}
    spec:
      {{- with .deployment.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: burrito-redis
      securityContext:
        {{- toYaml .deployment.podSecurityContext | nindent 8 }}
      containers:
        - name: redis
          command:
            {{- toYaml .deployment.command | nindent 12 }}
          args:
            {{- toYaml .deployment.args | nindent 12 }}
          securityContext:
            {{- toYaml .deployment.securityContext | nindent 12 }}
          image: "{{ .deployment.image.repository }}:{{ .deployment.image.tag }}"
          imagePullPolicy: {{ .deployment.image.pullPolicy }}
          ports:
            {{- toYaml .deployment.ports | nindent 12 }}
          livenessProbe:
            {{- toYaml .deployment.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .deployment.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .deployment.resources | nindent 12 }}
          env:
            {{- toYaml .deployment.env | nindent 12 }}
          envFrom:
            {{- toYaml .deployment.envFrom | nindent 12 }}
      {{- with .deployment.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .deployment.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .deployment.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- if .service.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: burrito-redis
  labels:
    {{- toYaml .metadata.labels | nindent 4}}
  annotations:
    {{- toYaml .metadata.annotations | nindent 4}}
spec:
  type: {{ .type }}
  ports:
    {{- toYaml .service.ports | nindent 4 }}
  selector:
    {{- toYaml .metadata.labels | nindent 4 }}
{{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: burrito-redis
  labels:
    {{- toYaml .metadata.labels | nindent 4 }}
  annotations:
    {{- toYaml .metadata.annotations | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: burrito-redis
  labels:
    {{- toYaml .metadata.labels | nindent 4 }}
  annotations:
    {{- toYaml .metadata.annotations | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: burrito-redis
subjects:
  - kind: ServiceAccount
    name: burrito-redis
    namespace: {{ $.Release.Namespace }}
{{- end }}
{{- end }}
