---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: runner
    app.kubernetes.io/name: burrito-runner
    app.kubernetes.io/part-of: burrito
  name: burrito-runner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: burrito-controllers
subjects:
  - kind: ServiceAccount
    name: burrito-runner
    namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: burrito-runner
  labels:
    app.kubernetes.io/component: runner
    app.kubernetes.io/name: burrito-runner
    app.kubernetes.io/part-of: burrito
