{{/*
Create ConfigMap in all tenant namespaces + release namespace
*/}}
{{- $namespaces := list }}
{{- range $tenant := .Values.tenants }}
{{- $namespaces = append $namespaces $tenant.namespace.name }}
{{- end }}
{{- $namespaces = append $namespaces .Release.Namespace }}

{{- range $namespace := $namespaces }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/part-of: burrito
    app.kubernetes.io/name: burrito-ssh-known-hosts
  name: burrito-ssh-known-hosts
  namespace: {{ $namespace }}
data:
  known_hosts: |-
    {{- $.Values.global.sshKnownHosts | nindent 4 }}
{{- end }}
