{{/*
Create ConfigMap in all tenant namespaces + release namespace
*/}}
{{- $namespaces := list }}
{{- range $tenant := .Values.tenants }}
{{- $namespaces = append $namespaces $tenant.namespace.name }}
{{- end }}
{{- $namespaces = append $namespaces .Release.Namespace }}

{{- range $namespace := $namespaces }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: burrito-ssh-known-hosts
  namespace: {{ $namespace }}
  labels:
    app.kubernetes.io/name: burrito-ssh-known-hosts
    {{- toYaml $.Values.global.metadata.labels | nindent 4 }}
  annotations:
    {{- toYaml $.Values.global.metadata.annotations | nindent 4 }}
data:
  known_hosts: |-
    {{- $.Values.global.sshKnownHosts | nindent 4 }}
{{- end }}
