metadata_dir = "/tmp/meta"
data_dir = "/data"
db_engine = "sqlite"
replication_factor = 1

rpc_bind_addr = "[::]:3901"
rpc_public_addr = "127.0.0.1:3901"
rpc_secret = "5deee1b6d1b2838b52be09d85fcdc0db2900303cca48811af7826dbee58dc9e8"

[s3_api]
s3_region = "eu-west-3"
api_bind_addr = "[::]:3900"
root_domain = ".s3.garage.localhost"
