apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: ghcr.io/padok-team/burrito
    newName: ghcr.io/padok-team/burrito
    newTag: main@sha256:8d4f222154efa4c50617f652b70c56cd0e85b1cd481367c52dee801753395fa6

resources:
  - ./controllers
  - ./server
  - ./runner
  - ./config
