apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: ghcr.io/padok-team/burrito
    newName: ghcr.io/padok-team/burrito
    newTag: main@sha256:3bc0885d8328d1b53e31e9f0055c2f7635cc3d5dceb5288470d7887cac7a724d

resources:
  - ./controllers
  - ./server
  - ./runner
  - ./config
