before:
  hooks:
  - go mod tidy
builds:
- env:
  - CGO_ENABLED=0
  - PACKAGE=github.com/padok-team/burrito
  ldflags:
  - -X ${PACKAGE}/internal/version.Version=${VERSION}
  - -X ${PACKAGE}/internal/version.CommitHash=${COMMIT_HASH}
  - -X ${PACKAGE}/internal/version.BuildTimestamp=${BUILD_TIMESTAMP}
  goos:
  - linux
  main: ./
  binary: burrito
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: '{{ .Tag }}-next'
changelog:
  sort: asc
  use: github
  groups:
  - title: Features
    regexp: "^.*(feat:|feat\\/|feat(\\([^\\)]*\\)):).*"
    order: 0
  - title: 'Bug fixes'
    regexp: "^.*(fix:|fix\\/|fix(\\([^\\)]*\\)):).*"
    order: 1
  - title: Others
    order: 999
  filters:
    exclude:
    - '^docs'
    - '^test'
    - '^style'
    - '^refactor'
    - '^build'
    - '^ci'
    - '^chore(release)'
