site_name: burrito
repo_url: https://github.com/padok-team/burrito
theme:
  name: material
  favicon: assets/icon/burrito.png
  logo: assets/icon/burrito.png
markdown_extensions:
- codehilite
- admonition
- toc:
    permalink: true
nav:
- Home: index.md
- Overview: overview.md
- Getting Started:
  - IaC Drift Detection: getting-started/iac-drift-detection.md
  - PR/MR Workflow: getting-started/pr-mr-workflow.md
  - UI Overview: getting-started/ui.md
- Operator Manual:
  - Install:
    - With static manifests: operator-manual/install/with-static-manifests.md
    - With our Helm chart: operator-manual/install/with-helm.md
  - operator-manual/index.md
  - operator-manual/architecture.md
  - operator-manual/git-webhook.md
  - operator-manual/advanced-configuration.md
  - operator-manual/multi-tenant-architecture.md
  - operator-manual/pr-mr-workflow.md
  - operator-manual/datastore.md
  - operator-manual/provider-caching.md
- User Guide:
  - user-guide/index.md
  - user-guide/override-runner.md
  - user-guide/remediation-strategy.md
  - user-guide/terraform-version.md
  - user-guide/private-modules.md
  - user-guide/additionnal-trigger-path.md
- Reference:
  - reference/api.md
  - reference/crds.md
- FAQ: faq.md
- Contributing:
  - contributing.md
