apiVersion: v1
kind: Pod
metadata:
  name: test
  namespace: burrito
spec:
  containers:
  - command: 
    - sleep
    args:
    - infinity
    env:
    - name: BURRITO_REDIS_URL
      value: burrito-redis-master:6379
    - name: BURRITO_REDIS_PASSWORD
    - name: BURRITO_REDIS_DATABASE
      value: "0"
    - name: BURRITO_RUNNER_REPOSITORY_URL
      value: git@github.com:padok-team/burrito.git
    - name: BURRITO_RUNNER_PATH
      value: internal/e2e/testdata/random-pets
    - name: BURRITO_RUNNER_BRANCH
      value: main
    - name: BURRITO_RUNNER_VERSION
      value: 1.3.1
    - name: BURRITO_RUNNER_LAYER_NAME
      value: random-pets
    - name: BURRITO_RUNNER_LAYER_NAMESPACE
      value: burrito
    - name: SSH_KNOWN_HOSTS
      value: /go/.ssh/known_hosts
    - name: BURRITO_RUNNER_ACTION
      value: plan
    - name: BURRITO_RUNNER_REPOSITORY_USERNAME
      valueFrom:
        secretKeyRef:
          key: username
          name: burrito-repo
          optional: true
    - name: BURRITO_RUNNER_REPOSITORY_PASSWORD
      valueFrom:
        secretKeyRef:
          key: password
          name: burrito-repo
          optional: true
    - name: BURRITO_RUNNER_REPOSITORY_SSHPRIVATEKEY
      valueFrom:
        secretKeyRef:
          key: sshPrivateKey
          name: burrito-repo
          optional: true
    image: eu.gcr.io/padok-playground/burrito:latest
    name: runner
    volumeMounts:
    - mountPath: /repository
      name: repository
    - mountPath: /go/.ssh/
      name: ssh-known-hosts
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-r8z27
      readOnly: true
    workingDir: /repository
  imagePullSecrets:
  - name: ghcr-creds
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Never
  schedulerName: gke.io/optimize-utilization-scheduler
  serviceAccountName: burrito-runner
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: repository
  - configMap:
      name: burrito-ssh-known-hosts
      optional: true
    name: ssh-known-hosts
  - name: kube-api-access-r8z27
    projected:
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              fieldPath: metadata.namespace
            path: namespace