config:
  burrito:
    runner:
      image:
        repository: burrito
        tag: "1783690876"
        pullPolicy: Never
    datastore:
      storage:
        mock: true
    controller:
      timers:
        driftDetection: 10m
        repositorySync: 2m
global:
  deployment:
    image:
      repository: burrito
      tag: "1783690876"
      pullPolicy: Never
tenants:
  - namespace:
      create: true
      name: "burrito-project"
