---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - config.terraform.padok.cloud
  resources:
  - terraformlayers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - config.terraform.padok.cloud
  resources:
  - terraformlayers/finalizers
  verbs:
  - update
- apiGroups:
  - config.terraform.padok.cloud
  resources:
  - terraformlayers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - config.terraform.padok.cloud
  resources:
  - terraformrepositories
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - config.terraform.padok.cloud
  resources:
  - terraformrepositories/finalizers
  verbs:
  - update
- apiGroups:
  - config.terraform.padok.cloud
  resources:
  - terraformrepositories/status
  verbs:
  - get
  - patch
  - update
