apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: redis
    app.kubernetes.io/name: burrito-redis
    app.kubernetes.io/part-of: burrito
  name: burrito-redis
  namespace: burrito
