apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: burrito-server
    app.kubernetes.io/part-of: burrito
  name: burrito-webhook-secret
  namespace: burrito
type: Opaque
