apiVersion: v1
kind: ServiceAccount
metadata:
  name: burrito-server
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: burrito-server
    app.kubernetes.io/part-of: burrito
