minimumReleaseAge: 10080 # 7 days
trustPolicy: no-downgrade
ignoreScripts: true

# We depend on semver@6.3.1 throughout the dependency graph and this version causes issue with attestation downgrade checks.
# See https://github.com/npm/node-semver/issues/886.
trustPolicyExclude:
  - semver

# `@swc/core` needs to be able to execute scripts during installation.
allowBuilds:
  "@swc/core": true
