name: Continuous Integration for Frontend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/ci-frontend.yaml"
      - "ui/**"

permissions: {}

jobs:
  build:
    name: Build UI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
      - name: Install pnpm and Node.js
        uses: pnpm/setup@84cb39b217b10273981911c288cd62326dc7c6d2 # v2.0.2
        with:
          cache: true
      - name: Run build
        run: pnpm --dir ui run build

  lint:
    name: Lint TS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
      - name: Install pnpm and Node.js
        uses: pnpm/setup@84cb39b217b10273981911c288cd62326dc7c6d2 # v2.0.2
        with:
          cache: true
      - name: Run oxlint
        run: pnpm --dir ui run lint
      - name: Run oxfmt
        run: pnpm --dir ui run format-check
