name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/build-and-push.yaml"
      - ".github/workflows/ci.yaml"
      - "**.go"
      - "go.mod"
      - "go.sum"
      - "Dockerfile"
      - "internal/e2e/docker-compose.yml"

permissions:
  packages: write
  id-token: write # Required for Codecov and keyless cosign signing (build-and-push.yaml)

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Cache envtest binaries
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6
        with:
          path: ./bin/
          key: binaries
      - name: Setup Golang
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7
        with:
          go-version-file: "go.mod"
      - name: Install envtest
        run: make envtest
      - name: Setup envtest
        run: ./bin/setup-envtest use
      - name: Set up Docker Buildx for docker compose
        uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4
      - name: Run tests
        run: make test
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7
        with:
          use_oidc: true

  check-codegen:
    name: Check Codegen
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Setup Golang
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7
        with:
          go-version-file: "go.mod"
      - name: Generate manifests
        run: make manifests
      - name: Check nothing has changed
        run: |
          git diff --exit-code ./manifests

  lint-go:
    name: Lint Go
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7
        with:
          go-version-file: "go.mod"
      - name: golangci-lint
        uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9
        with:
          version: latest
          args: --issues-exit-code=0

  build-and-push:
    uses: ./.github/workflows/build-and-push.yaml
