name: Conventional Commits check

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Install pnpm and Node.js
        uses: pnpm/setup@703c52620218391530e48b9e8870d5c0082e1b9b # v2.1.0
        with:
          cache: true
      - name: Generate commitlint configuration
        run: |
          echo "export default { extends: ['@commitlint/config-conventional'] };" > commitlint.config.js
      - name: commitlint (run)
        run: pnpm commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose
