name: Docker Build

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          load: true
          tags: burrito:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
