name: Release

on:
  push:
    tags:
    - 'v*'

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    environment: production
    steps:

    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Fetch all tags
      run: git fetch --force --tags

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v3
      with:
        distribution: goreleaser
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Bump version
      run: |
        echo ${{ github.ref_name }} > VERSION
    - name: Commit version to repository
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_messsage: "chore(release): bump version to ${{ github.ref_name }}""
