name: Pull Request Continuous Integration

on:
  pull_request:
    branches:
    - main

env:
  GO_VERSION: 1.22
  BUILD_PLATFORMS: linux/amd64,linux/arm64

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
    - name: Cache envtest binaries
      uses: actions/cache@e12d46a63a90f2fae62d114769bbf2a179198b5c # v3
      with:
        path: ./bin/
        key: binaries
    - name: Setup Golang
      uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4
      with:
        go-version: "${{ env.GO_VERSION }}"
    - name: Install envtest
      run: make envtest
    - name: Setup envtest
      run: ./bin/setup-envtest use
    - name: Run tests
      run: make test
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@ab904c41d6ece82784817410c45d8b8c02684457 # v3

  check-codegen:
    name: Check Codegen
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
    - name: Setup Golang
      uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4
      with:
        go-version: "${{ env.GO_VERSION }}"
    - name: Generate manifests
      run: make manifests
    - name: Check nothing has changed
      run: |
        git diff --exit-code ./manifests

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4
        with:
          go-version: "${{ env.GO_VERSION }}"
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@3a919529898de77ec3da873e3063ca4b10e7f5cc # v3
        with:
          version: v1.55
          args: --timeout=5m

  build-and-push:
    name: Build & Push
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

    - name: Get Build timestamp and branch name
      run: |
        echo "BUILD_TIMESTAMP=$(date +'%s')" >> $GITHUB_ENV
        echo "VERSION=$( echo ${{ github.head_ref || github.ref_name }} | tr '/' '-' )" >> $GITHUB_ENV

    - name: Docker tags & labels
      id: meta
      uses: docker/metadata-action@818d4b7b91585d195f67373fd9cb0332e31a7175 # v4
      with:
        images: ghcr.io/${{ github.repository }}
        # generate Docker tags:
        # - type=raw,VERSION -> branch name
        # - type=ref,event=tag -> tag name
        # - type=sha,format=long,prefix= -> commit sha
        tags: |
          type=raw,${{ env.VERSION }}
          type=ref,event=tag
          type=sha,format=long,prefix=

    - name: Set up QEMU
      uses: docker/setup-qemu-action@2b82ce82d56a2a04d2637cd93a637ae1b359c0a7 # v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@885d1462b80bc1c1c7f0b00334ad271f09369c55 # v2

    - name: Login to GHCR
      uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@0a97817b6ade9f46837855d676c4cca3a2471fc9 # v4
      with:
        provenance: false
        platforms: ${{ env.BUILD_PLATFORMS }}
        build-args: |
          VERSION=${{ env.VERSION }}
          BUILD_TIMESTAMP=${{ env.BUILD_TIMESTAMP }}
          COMMIT_HASH=${{ github.sha }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
